/*
Programmer: Siddhi Patel
Date: April 17, 2025
Program Name: Student Grades
Program Description: This program uses arrays to stimulate a grade book for a class with any number of students who each have four test scores.
* The user is able to enter the student's first and last name along with their grades in the four courses.
* An add button adds the inputted student information into a 2d array.
* A list button allows the user to see all the student information for all the students.
* A course average button calculates and displays the average for each of the four courses.
* A student average button allows the user to enter a student's first and last name to calculate and display their average.
 */
package studentgrades;


/**
 *
 * @author Siddhi
 */
public class StudentGrades extends javax.swing.JFrame {
    //initial array with a variable number of rows and fixed columns
    String[][] students = new String[0][6]; 
    
    /* Method to clear the input text fields after student data has been added */
    private void clearTextFields(){
        txtFirstNameInput.setText("");
        txtLastNameInput.setText("");
        txtCourse1Input.setText("");
        txtCourse2Input.setText("");
        txtCourse3Input.setText("");
        txtCourse4Input.setText("");
    }
    /**
     * Creates new form StudentGrades
     */
    public StudentGrades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtFirstNameInput = new javax.swing.JTextField();
        txtLastNameInput = new javax.swing.JTextField();
        lblCourse1 = new javax.swing.JLabel();
        lblCourse2 = new javax.swing.JLabel();
        lblCourse3 = new javax.swing.JLabel();
        lblCourse4 = new javax.swing.JLabel();
        txtCourse1Input = new javax.swing.JTextField();
        txtCourse2Input = new javax.swing.JTextField();
        txtCourse3Input = new javax.swing.JTextField();
        txtCourse4Input = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnStudentAvg = new javax.swing.JButton();
        btnCourseAvg = new javax.swing.JButton();
        Output = new javax.swing.JScrollPane();
        OutputList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Grades Application");

        Title.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Title.setForeground(new java.awt.Color(204, 139, 4));
        Title.setText("Student Grades");

        lblFirstName.setText("First Name:");

        lblLastName.setText("Last Name:");

        lblCourse1.setText("Course 1:");

        lblCourse2.setText("Course 2:");

        lblCourse3.setText("Course 3:");

        lblCourse4.setText("Course 4:");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnStudentAvg.setText("Student Average");
        btnStudentAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentAvgActionPerformed(evt);
            }
        });

        btnCourseAvg.setText("Course Average");
        btnCourseAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseAvgActionPerformed(evt);
            }
        });

        OutputList.setColumns(20);
        OutputList.setRows(5);
        OutputList.setPreferredSize(new java.awt.Dimension(1000, 600));
        Output.setViewportView(OutputList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(Title))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCourse1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCourse1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCourse2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCourse2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCourse3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCourse3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCourse4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCourse4Input, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnList)
                                            .addComponent(btnAdd))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnStudentAvg)
                                            .addComponent(btnCourseAvg)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addComponent(btnExit)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName)
                            .addComponent(txtLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourse1)
                            .addComponent(txtCourse1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourse2)
                            .addComponent(txtCourse2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourse3)
                            .addComponent(txtCourse3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourse4)
                            .addComponent(txtCourse4Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnStudentAvg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnList)
                            .addComponent(btnCourseAvg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit)
                        .addGap(29, 29, 29)))
                .addComponent(Output, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); //exits the application
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        /* Gets the user input */
        String firstName = txtFirstNameInput.getText();
        String lastName = txtLastNameInput.getText();
        String grade1 = txtCourse1Input.getText();
        String grade2 = txtCourse2Input.getText();
        String grade3 = txtCourse3Input.getText();
        String grade4 = txtCourse4Input.getText();
        
        String[][] newStudents = new String[students.length +1][6]; //creates a new array with one extra row
        
        /* Copies the data from the original array */
        for(int i = 0; i < students.length; i++){
            for (int j = 0; j < 6; j++){
               newStudents[i][j] = students[i][j]; 
            }
        }
        
        /* Adds data of the new student in the last row of the array */
        newStudents[students.length][0] = firstName;
        newStudents[students.length][1] = lastName;
        newStudents[students.length][2] = grade1;
        newStudents[students.length][3] = grade2;
        newStudents[students.length][4] = grade3;
        newStudents[students.length][5] = grade4;
        
        students = newStudents; //replaces old array with new updated one
        clearTextFields(); //clears the input fields to make it easier to add another student's data
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        StringBuilder output = new StringBuilder(); //variable for output string
        for(int i = 0; i < students.length; i++){ //for all the students (rows) in the array, add their information to the output string
            output.append(students[i][0]).append(" ").append(students[i][1]).append(" --------->       C1: "); //adds the first and last name with spaces in between
            output.append(students[i][2]).append("%       C2: ").append(students[i][3]).append("%       C3: "); //adds grades for courses 1 and 2 with spaces in between
            output.append(students[i][4]).append("%       C4: ").append(students[i][5]).append("% \n"); //adds grades for courses 3 and 4 with spaces in between
        }
        OutputList.setText(output.toString()); //displays output list with all the students and their grades in all courses
    }//GEN-LAST:event_btnListActionPerformed

    private void btnStudentAvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentAvgActionPerformed
        StringBuilder output = new StringBuilder(); //variable for output string
        
        String firstName = txtFirstNameInput.getText(); //gets the input for student's first name
        String lastName = txtLastNameInput.getText(); //gets the input for student's last name
        
        double sum = 0; //creates a variable for the sum of all of a student's grades
        
        for(int i = 0; i < students.length; i++){ //to search for all the students in the array 
            if(students[i][0].equalsIgnoreCase(firstName) && students[i][1].equalsIgnoreCase(lastName)){ //if the inputted first and last names match a specific cell in the array
                output.append(students[i][0]).append(" ").append(students[i][1]).append(":\n     C1: "); //adds the first and last name of the student
                output.append(students[i][2]).append("%       C2: ").append(students[i][3]).append("%       C3: "); //adds grades for courses 1 and 2 for the student
                output.append(students[i][4]).append("%       C4: ").append(students[i][5]).append("% "); //adds grades for courses 3 and 4 for the student
                for(int j = 2; j < 6; j ++){ //for all 4 courses
                    sum += Double.parseDouble(students[i][j]); //adds up the grades in all 4 courses for the student
                }
                double average = sum/4; //calculates the student's average of the 4 courses 
                output.append("    Average: ").append(String.format("%.2f",average)).append("%").append("\n"); //diplays the student's average
            }
        }
        
        output.append("\n=================================================\n All Student Information: \n"); //line separator for displaying the all of the student information stored
        
        /* Displays all the stored student information for all students below the inputted student's average */
        for(int i = 0; i < students.length; i++){ //for all the students (rows) in the array, add their information to the output string
            output.append(students[i][0]).append(" ").append(students[i][1]).append(" --------->       C1: "); //adds the first and last name with spaces in between
            output.append(students[i][2]).append("%       C2: ").append(students[i][3]).append("%       C3: "); //adds grades for courses 1 and 2 with spaces in between
            output.append(students[i][4]).append("%       C4: ").append(students[i][5]).append("% \n"); //adds grades for courses 3 and 4 with spaces in between
        }
        
        OutputList.setText(output.toString()); //displays output list with the entered student's average and all the students and their grades in all courses
    }//GEN-LAST:event_btnStudentAvgActionPerformed

    private void btnCourseAvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseAvgActionPerformed
        StringBuilder output = new StringBuilder(); //variable for output string
        
        /* Displays all the stored student information for all students with their averages*/
        for(int i = 0; i < students.length; i++){ //for all the students (rows) in the array, add their information to the output string
            output.append(students[i][0]).append(" ").append(students[i][1]).append(" --------->     C1: "); //adds the first and last name with spaces in between
            output.append(students[i][2]).append("%       C2: ").append(students[i][3]).append("%       C3: "); //adds grades for courses 1 and 2 with spaces in between
            output.append(students[i][4]).append("%       C4: ").append(students[i][5]).append("% "); //adds grades for courses 3 and 4 with spaces in between
            
            double sum = 0; //creates a variable for the sum of all of a student's grades
            
            for(int j = 2; j < 6; j ++){ //for all 4 courses
                sum += Double.parseDouble(students[i][j]); //adds up the grades in all 4 courses of each student
            }
            double average = sum/4; //calculates the average of the 4 courses for each student
            output.append("    Average: ").append(String.format("%.2f",average)).append("%").append("\n"); //diplays each student's average rounded to 2 decimal places beside their grades 
        }
        
        output.append("\n=================================================\nCourse Averages:\n"); //line separator for student information and course averages
        
        for(int j = 2; j < 6; j++){ //for all 4 courses
            double total = 0; //creates a variable for the total of the grades in each course
            for(int i = 0; i < students.length; i++){ //for each student (row) in the array
                total += Double.parseDouble(students[i][j]); //adds the grades of each student to the total of each course
            }
            double average = total/students.length; //calculates the average of each course
            output.append("    Course ").append(j-1).append(" Average: ").append(String.format("%.2f",average)).append("%").append("\n"); //adds the course averages rounded to 2 decimal places to the output
        }
        OutputList.setText(output.toString()); //displays output list with all the students and their grades in all courses
    }//GEN-LAST:event_btnCourseAvgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Output;
    private javax.swing.JTextArea OutputList;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCourseAvg;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnStudentAvg;
    private javax.swing.JLabel lblCourse1;
    private javax.swing.JLabel lblCourse2;
    private javax.swing.JLabel lblCourse3;
    private javax.swing.JLabel lblCourse4;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JTextField txtCourse1Input;
    private javax.swing.JTextField txtCourse2Input;
    private javax.swing.JTextField txtCourse3Input;
    private javax.swing.JTextField txtCourse4Input;
    private javax.swing.JTextField txtFirstNameInput;
    private javax.swing.JTextField txtLastNameInput;
    // End of variables declaration//GEN-END:variables
}
